server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Compressão Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Se for um crawler de rede social, servimos o index.html (que tem as meta tags)
        # Isso evita que o crawler se perca em rotas do React
        if ($http_user_agent ~* "facebookexternalhit|WhatsApp|Facebot|Twitterbot") {
            rewrite ^ /index.html break;
        }

        # Suporte para roteamento do React (SPA)
        try_files $uri $uri/ /index.html;
    }

    # Cache para arquivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Página de erro padrão
    error_page 404 /index.html;
}