// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aoghhoqiwjwqfjifaait.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZ2hob3Fpd2p3cWZqaWZhYWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNjQ4NDgsImV4cCI6MjA4Njg0MDg0OH0.yO5vHHEcsIKIoHOne6MxXtqhw1WH1WlRi1JRz_fkhhw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);